services:
  - type: web
    name: swiss-airlines-va
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: Gregory
      - key: ADMIN_PASS
        value: 123789
